apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth
          imagePullPolicy: Never
          env:
          - name: APP_PORT
            value: "3000"
          - name: MONGO_HOST
            value: "auth-mongo-srv"
          - name: MONGO_PORT
            value: "27017"
          - name: NATS_HOST
            value: "nats-srv"
          - name: NATS_PORT
            value: "4222"           
          - name: REDIS_HOST
            value: "auth-redis-srv"
          - name: REDIS_PORT
            value: "6379"


---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000